changesetIgnorePatterns:
  - "**/*.{test}.{js,ts,jsx,tsx}"
  - "!(.yarn/versions/**|src/**/*|package.json|.swcrc*)"
  - .yarn/versions/f6aa7e9c.yml
  - .yarn/versions/a381b761.yml

nodeLinker: node-modules
